"theme:workflow":
  - changed-files:
      - any-glob-to-any-file: ".github/**"

"theme:build":
  - changed-files:
      - any-glob-to-any-file:
          - ".editorconfig"
          - ".oxlintrc.json"
          - ".oxfmtrc.jsonc"
          - ".oxfmtignore"
          - ".gitignore"
          - "package.json"
          - "tsconfig.json"
          - ".husky/**"

"theme:plugin":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/plugin-allure2/**"
          - "packages/plugin-classic/**"
          - "packages/plugin-csv/**"
          - "packages/plugin-dashboard/**"
          - "packages/plugin-jira/**"
          - "packages/plugin-log/**"
          - "packages/plugin-progress/**"
          - "packages/plugin-server-reload/**"
          - "packages/plugin-slack/**"
          - "packages/plugin-testplan/**"

"theme:cli":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/plugin-log/**"
          - "packages/plugin-progress/**"
          - "packages/cli/**"

"theme:reader":
  - changed-files:
      - any-glob-to-any-file: "packages/reader/**"

"theme:awesome":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/plugin-awesome/**"
          - "packages/web-awesome/**"

"theme:dashboard":
  - changed-files:
      - any-glob-to-any-file:
          - "packages/plugin-dashboard/**"
          - "packages/web-dashboard/**"

"theme:testops":
  - changed-files:
      - any-glob-to-any-file: "packages/plugin-testops/**"
