compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: backbone*1.6.0*
  - level: discard
    pattern: underscore*1.13.6*

packageExtensions:
  backbone@*:
    peerDependencies:
      jquery: "*"
  svg-sprite-loader@*:
    dependencies:
      webpack: "*"
  "@nivo/line@*":
     dependencies:
       lodash: "*"
  "@testing-library/jest-dom@*":
     dependencies:
       vitest: "*"
  "@prefresh/core@*":
     dependencies:
       preact: "*"

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.5.1.cjs

npmPublishRegistry: https://registry.npmjs.org
