compressionLevel: mixed

enableGlobalCache: false

logFilters:
  - level: discard
    pattern: backbone*1.6.0*
  - level: discard
    pattern: underscore*1.13.6*

npmPublishRegistry: "https://registry.npmjs.org"

packageExtensions:
  "@nivo/line@*":
    dependencies:
      lodash: "*"
  "@prefresh/core@*":
    dependencies:
      preact: "*"
  "@testing-library/jest-dom@*":
    dependencies:
      vitest: "*"
  backbone@*:
    peerDependencies:
      jquery: "*"
  svg-sprite-loader@*:
    dependencies:
      webpack: "*"

plugins:
  - ./plugin-ci-version.cjs

supportedArchitectures:
  cpu:
    - current
    - x64
    - arm64
  libc:
    - current
    - glibc
    - musl
  os:
    - current
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.10.3.cjs
