name: Build project

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable --immutable-cache --check-cache
      - name: Lint Project
        run: yarn eslint

  test:
    needs: lint
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      ALLURE_SERVICE_URL: ${{ secrets.ALLURE_SERVICE_URL }}
      ALLURE_SERVICE_ACCESS_TOKEN: ${{ secrets.ALLURE_SERVICE_ACCESS_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Install playwright for static server
      run: yarn workspace @allurereport/static-server playwright install chromium
    - name: Install playwright for e2e
      run: yarn workspace @allurereport/e2e playwright install chromium firefox webkit
    - name: Install playwright dependencies for e2e
      run: yarn workspace @allurereport/e2e playwright install-deps
    - name: Build project
      run: yarn build
    - name: Test Project
      run: yarn test
    - name: Pack test results
      run: yarn allure results pack --name allure-results-${{ matrix.os }}.zip "**/out/allure-results"
    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: allure-results-${{ matrix.os }}
        path: ./allure-results.zip

  report:
    needs: test
    name: Build report
    runs-on: ubuntu-latest
    env:
      ALLURE_SERVICE_URL: ${{ secrets.ALLURE_SERVICE_URL }}
      ALLURE_SERVICE_ACCESS_TOKEN: ${{ secrets.ALLURE_SERVICE_ACCESS_TOKEN }}
    steps:
      - name: Download allure results from Ubuntu
        uses: actions/download-artifact@v4
        with:
          name: allure-results-ubuntu-latest
          path: ./
      - name: Download allure results from macOS
        uses: actions/download-artifact@v4
        with:
          name: allure-results-macos-latest
          path: ./
      - name: Download allure results from Windows
        uses: actions/download-artifact@v4
        with:
          name: allure-results-windows-latest
          path: ./
      - name: List test results
        run: ls -R
