name: Build project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20.x'
        cache: 'yarn'
    - name: Install dependencies
      run: yarn install --immutable --immutable-cache --check-cache
    - name: Install playwright for static server
      run: yarn workspace @allurereport/static-server playwright install chromium
    - name: Install playwright for e2e
      run: yarn workspace @allurereport/e2e playwright install chromium firefox webkit
    - name: Install playwright dependencies for e2e
      run: yarn workspace @allurereport/e2e playwright install-deps
    - name: Build project
      run: yarn build
    - name: Test Project
      run: yarn test
    - name: Lint Project
      run: yarn eslint
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./out/allure-report/awesome
        publish_branch: gh-pages
